remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Natielle Caetano
author: João Lyma


navbar-links:
  Home: "/"
  Hire me: "https://www.linkedin.com/in/natielle-caetano-a96770125/"
  Projects: "projects"
  About Me / Contact: "aboutme"
  ❤ Support: "https://github.com/sponsors/lyma"

avatar: "/assets/img/natty.jpg"

social-network-links:
  email: "natielle@natielle.com.br"
  facebook: natielle.silva.94
  github: lyma
  twitter: lymas
  linkedin: "natielle-caetano-a96770125"
  #stackoverflow: "users/3943160/daattali"
  #calendly: "attalitech/meeting"
  #youtube: "c/daattali?sub_confirmation=1"
  #patreon: DeanAttali

share-links-active:
  twitter: false
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "r shiny,r shiny developer,shiny developer,shiny apps,shiny consultant,dashboards r,interactive dashboards"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

edit_page_button: true

timezone: "America/Toronto"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

disqus: "deanattali-site"
google_analytics: "UA-59820529-1"
fb_app_id: "536330676521989"

url-pretty: "❤ Support"
url-canonical: https://github.com/sponsors/lyma

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: false
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
